version: "3.8"

services:
  backend:
    build: ./server
    container_name: flask_api
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      - FLASK_ENV=production
    restart: always

  frontend:
    build: ./client
    container_name: react_app
    volumes:
      - ./client:/app
      - /app/node_modules  
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

